
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _STAGE_NAME: ""
  _ARTIFACT_REGISTRY_LOCATION: ""
  _ARTIFACT_REGISTRY_DOCKER: ""
  _ARTIFACT_REGISTRY_PYPI: ""
  _IMAGE_NAME: ""

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/uv-index-gcp-username/versions/latest
      env: UV_INDEX_GCP_USERNAME
    - versionName: projects/$PROJECT_ID/secrets/uv-index-gcp-password/versions/latest
      env: UV_INDEX_GCP_PASSWORD

timeout: 2400s
steps:
  - name: ${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_DOCKER}/${_IMAGE_NAME}
    secretEnv:
      - UV_INDEX_GCP_USERNAME
      - UV_INDEX_GCP_PASSWORD
    env:
      - HAS_IMAGE=true
      - HAS_PACKAGE=true
      - TEST_KIND=in_image
      - PROJECT_ID=$PROJECT_ID
      - STAGE_NAME=${_STAGE_NAME}
      - ARTIFACT_REGISTRY_LOCATION=${_ARTIFACT_REGISTRY_LOCATION}
      - ARTIFACT_REGISTRY_DOCKER=${_ARTIFACT_REGISTRY_DOCKER}
      - ARTIFACT_REGISTRY_PYPI=${_ARTIFACT_REGISTRY_PYPI}
