
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _STAGE_NAME: ""
  _ARTIFACT_REGISTRY_LOCATION: ""
  _ARTIFACT_REGISTRY_DOCKER: ""
  _ARTIFACT_REGISTRY_PYPI: ""
  _IMAGE_NAME: ""

timeout: 2400s
steps:
  - name: ${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_DOCKER}/${_IMAGE_NAME}
    env:
      - HAS_IMAGE=true
      - HAS_PACKAGE=true
      - TEST_KIND=in_image
      - PROJECT_ID=$PROJECT_ID
      - STAGE_NAME=${_STAGE_NAME}
      - ARTIFACT_REGISTRY_LOCATION=${_ARTIFACT_REGISTRY_LOCATION}
      - ARTIFACT_REGISTRY_DOCKER=${_ARTIFACT_REGISTRY_DOCKER}
      - ARTIFACT_REGISTRY_PYPI=${_ARTIFACT_REGISTRY_PYPI}
